/**
 * Gate 0: validation boundary for future PAS-derived Professional charts.
 * No values, predictions or recommendations are generated by this module.
 * The UI must never compare observations rejected by canCompareVisualMetrics.
 */
export const VISUAL_PANEL_IDS = [
  'V01', 'V02', 'V03', 'V04', 'V05', 'V06', 'V07', 'V08', 'V09',
  'V10', 'V11', 'V12', 'V13', 'V14', 'V15', 'V16', 'V17', 'V18', 'V19',
] as const;

export type VisualPanelId = (typeof VISUAL_PANEL_IDS)[number];
export type VisualPanelState =
  | 'AVAILABLE'
  | 'PARTIAL_COMPARISON'
  | 'STALE'
  | 'NON_COMPARABLE'
  | 'INSUFFICIENT_EVIDENCE'
  | 'HELD';
export type VisualMetricKind =
  | 'EMPLOYMENT_GROWTH_PERCENT'
  | 'NET_NEW_JOBS'
  | 'ANNUAL_OPENINGS'
  | 'MEDIAN_GROSS_MONTHLY_SALARY';
export type VisualGeography =
  | 'US_BENCHMARK'
  | 'ARGENTINA_LOCAL'
  | 'ARGENTINA_DOLLARIZED_REMOTE'
  | 'LATAM_REMOTE'
  | 'INTERNATIONAL_REMOTE';
export type VisualHorizon = 'OFFICIAL_2025_2035' | 'HISTORICAL_SURVEY';

/** Numbers are observations or external official projections, never AI-risk probabilities. */
export interface VisualMetric {
  id: string;
  label: string;
  kind: VisualMetricKind;
  value: number;
  unit: 'PERCENT' | 'JOBS' | 'JOBS_PER_YEAR' | 'ARS_GROSS_MONTHLY';
  geography: VisualGeography;
  horizon: VisualHorizon;
  period: string;
  roleId: string;
  occupationCode: string | null;
  seniority: string | null;
  dollarized: boolean | null;
  sampleSize: number | null;
  sourceId: string;
}

export interface VisualSource {
  id: string;
  label: string;
  url: string;
  observedAt: string;
  reviewAfterDays: number;
  kind: 'OFFICIAL_STATISTICS' | 'WORKFORCE_SURVEY';
}

export interface VisualPanel {
  id: VisualPanelId;
  state: VisualPanelState;
  reason: string | null;
  metrics: VisualMetric[];
}

export interface ProfessionalVisualizationSnapshot {
  schemaVersion: 1;
  kind: 'professional_visualization_snapshot';
  source: {
    repository: 'franciscovitar/personal-ai-system';
    ref: 'main';
    commit: string;
    canonicalRefs: string[];
    generatedAt: string;
  };
  sources: VisualSource[];
  panels: VisualPanel[];
}

function record(x: unknown): x is Record<string, unknown> {
  return typeof x === 'object' && x !== null && !Array.isArray(x);
}
function string(x: unknown): x is string {
  return typeof x === 'string' && x.trim().length > 0;
}
function number(x: unknown): x is number {
  return typeof x === 'number' && Number.isFinite(x);
}
const panelIds = new Set<string>(VISUAL_PANEL_IDS);
const panelStates = new Set<string>([
  'AVAILABLE', 'PARTIAL_COMPARISON', 'STALE', 'NON_COMPARABLE',
  'INSUFFICIENT_EVIDENCE', 'HELD',
]);
const places = new Set<string>([
  'US_BENCHMARK', 'ARGENTINA_LOCAL', 'ARGENTINA_DOLLARIZED_REMOTE',
  'LATAM_REMOTE', 'INTERNATIONAL_REMOTE',
]);
const date = (x: unknown): x is string => {
  if (!string(x) || !/^\d{4}-\d{2}-\d{2}$/.test(x)) return false;
  const parsed = new Date(x + 'T00:00:00Z');
  return !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === x;
};

function validMetric(x: unknown): x is VisualMetric {
  if (!record(x)) return false;
  if (!string(x.id) || !string(x.label) || !number(x.value) ||
      !places.has(String(x.geography)) || !string(x.period) ||
      !string(x.roleId) || !string(x.sourceId) ||
      (x.occupationCode !== null && !string(x.occupationCode)) ||
      (x.seniority !== null && !string(x.seniority)) ||
      (x.sampleSize !== null && (!Number.isInteger(x.sampleSize) || Number(x.sampleSize) < 1)) ||
      (x.dollarized !== null && typeof x.dollarized !== 'boolean')) return false;

  const projected = x.kind === 'EMPLOYMENT_GROWTH_PERCENT' ||
    x.kind === 'NET_NEW_JOBS' || x.kind === 'ANNUAL_OPENINGS';
  if (projected) {
    return x.geography === 'US_BENCHMARK' &&
      x.horizon === 'OFFICIAL_2025_2035' && x.period === '2025-2035' &&
      x.sampleSize === null && x.seniority === null && x.dollarized === null &&
      typeof x.occupationCode === 'string' && /^\d{2}-\d{4}$/.test(x.occupationCode) &&
      ((x.kind === 'EMPLOYMENT_GROWTH_PERCENT' && x.unit === 'PERCENT' && x.value >= -100) ||
        (x.kind === 'NET_NEW_JOBS' && x.unit === 'JOBS' && Number.isInteger(x.value)) ||
        (x.kind === 'ANNUAL_OPENINGS' && x.unit === 'JOBS_PER_YEAR' &&
          Number.isInteger(x.value) && x.value >= 0));
  }
  if (x.kind === 'MEDIAN_GROSS_MONTHLY_SALARY') {
    return (x.geography === 'ARGENTINA_LOCAL' || x.geography === 'ARGENTINA_DOLLARIZED_REMOTE') &&
      x.horizon === 'HISTORICAL_SURVEY' && x.unit === 'ARS_GROSS_MONTHLY' &&
      x.occupationCode === null && string(x.seniority) &&
      Number.isInteger(x.sampleSize) && Number(x.sampleSize) >= 1 &&
      typeof x.dollarized === 'boolean' && x.value >= 0;
  }
  return false;
}

/** Fail-closed: blocks mixed geography, period, seniority and source/method. */
export function canCompareVisualMetrics(a: VisualMetric, b: VisualMetric): boolean {
  if (!validMetric(a) || !validMetric(b)) return false;
  return a.kind === b.kind && a.unit === b.unit &&
    a.geography === b.geography && a.horizon === b.horizon &&
    a.period === b.period && a.sourceId === b.sourceId &&
    a.seniority === b.seniority && a.dollarized === b.dollarized;
}

/** Return null on any contradictory or untraceable numeric input; no fallback dataset. */
export function parseProfessionalVisualizationSnapshot(value: unknown): ProfessionalVisualizationSnapshot | null {
  if (!record(value) || value.schemaVersion !== 1 ||
      value.kind !== 'professional_visualization_snapshot' ||
      !record(value.source) ||
      value.source.repository !== 'franciscovitar/personal-ai-system' ||
      value.source.ref !== 'main' ||
      !string(value.source.commit) || !/^[a-f0-9]{40}$/.test(value.source.commit) ||
      !date(value.source.generatedAt) ||
      !Array.isArray(value.source.canonicalRefs) || value.source.canonicalRefs.length < 1 ||
      !value.source.canonicalRefs.every((x: unknown) => string(x) && x.startsWith('AI/projects/professional-intelligence/')) ||
      !Array.isArray(value.sources) || !Array.isArray(value.panels)) return null;
  const sources = value.sources as unknown[];
  const ids = new Set<string>();
  for (const item of sources) {
    if (!record(item) || !string(item.id) || ids.has(item.id) || !string(item.label) ||
        !string(item.url) || !item.url.startsWith('https://') || !date(item.observedAt) ||
        !Number.isInteger(item.reviewAfterDays) || Number(item.reviewAfterDays) < 1 ||
        !['OFFICIAL_STATISTICS', 'WORKFORCE_SURVEY'].includes(String(item.kind))) return null;
    ids.add(item.id);
  }
  const panelSeen = new Set<string>();
  const metricSeen = new Set<string>();
  for (const item of value.panels) {
    if (!record(item) || !panelIds.has(String(item.id)) || panelSeen.has(String(item.id)) ||
        !panelStates.has(String(item.state)) ||
        (item.reason !== null && !string(item.reason)) || !Array.isArray(item.metrics)) return null;
    panelSeen.add(String(item.id));
    // Panels with no trustworthy data can be rendered as explanations, not empty charts.
    if ((item.state === 'AVAILABLE' && item.metrics.length === 0) ||
        (item.state !== 'AVAILABLE' && item.reason === null)) return null;
    for (const metric of item.metrics) {
      if (!validMetric(metric) || metricSeen.has(metric.id) || !ids.has(metric.sourceId)) return null;
      metricSeen.add(metric.id);
      const source = sources.find((src) => record(src) && src.id === metric.sourceId) as Record<string, unknown>;
      if ((metric.kind === 'MEDIAN_GROSS_MONTHLY_SALARY' && source.kind !== 'WORKFORCE_SURVEY') ||
          (metric.kind !== 'MEDIAN_GROSS_MONTHLY_SALARY' && source.kind !== 'OFFICIAL_STATISTICS')) return null;
    }
  }
  return value as unknown as ProfessionalVisualizationSnapshot;
}

/** A review trigger, never permission to re-label a historical survey as current. */
export function isVisualSourceReviewDue(source: VisualSource, now = new Date()): boolean {
  if (!date(source.observedAt) || !Number.isInteger(source.reviewAfterDays) ||
      source.reviewAfterDays < 1) return true;
  const observed = new Date(source.observedAt + 'T00:00:00Z').getTime();
  const elapsed = now.getTime() - observed;
  return !Number.isFinite(elapsed) || elapsed < 0 ||
    elapsed > source.reviewAfterDays * 24 * 60 * 60 * 1000;
}
